# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-11 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[['pending', 'Pending'], ['in_progress', 'In Progress'], ['done', 'Done']], default='pending', max_length=256),
        ),
    ]
