# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-17 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0002_contactrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='view',
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
