# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-17 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0003_contactrequest_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
