# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 04:20
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField()),
                ('gst', models.DecimalField(decimal_places=3, max_digits=5)),
                ('is_published', models.BooleanField(default=True)),
                ('currency_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CleaningExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
                ('hours', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CleaningHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_hours', models.DecimalField(decimal_places=2, default=Decimal('4.0'), max_digits=4)),
                ('min_rooms', models.IntegerField(default=3)),
                ('increment', models.DecimalField(decimal_places=2, default=Decimal('0.5'), max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='CleaningPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_months', models.IntegerField(blank=True, choices=[(3, '3 Months'), (6, '6 Months'), (12, '12 Months')], null=True)),
                ('sessions_per_week', models.IntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricing.City')),
            ],
        ),
    ]
