# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('zip', models.CharField(blank=True, max_length=128, null=True)),
                ('schedule', models.IntegerField(choices=[(1, 'Once per week'), (2, 'Twice per week'), (3, 'Three times per week')], default=1)),
                ('months', models.IntegerField(choices=[(3, '3 Months'), (6, '6 Months'), (12, '12 Months')], default=3)),
                ('num_bedrooms', models.IntegerField()),
                ('num_bathrooms', models.IntegerField()),
                ('num_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('first_visit', models.DateTimeField(blank=True, null=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_address', models.TextField(blank=True, null=True)),
                ('calculated_quote', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('failed', 'Failed'), ('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=30, null=True)),
                ('stripe_card', models.CharField(blank=True, max_length=256)),
                ('stripe_customer', models.CharField(blank=True, max_length=256)),
                ('stripe_error', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CleaningRequestExtras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('hours', models.IntegerField()),
                ('cleaning_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='cleaning_requests.CleaningRequest')),
            ],
        ),
    ]
