# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-20 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('failed', 'Failed'), ('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=30, null=True),
        ),
    ]
