# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-22 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_requests', '0002_auto_20180420_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningrequest',
            name='currency_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
